name: Docker Image CI

on: [push]

# Environment variables available to all jobs and steps in this workflow
env:
  REGISTRY_NAME: githubactionspov
  CLUSTER_NAME: aksdemogithub
  CLUSTER_RESOURCE_GROUP: GithubDemo
  NAMESPACE: mydemoapp
  SECRET: githubdemosecret
  APP_NAME: demoapp
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main
    - name: Run DevSkim scanner
      uses: microsoft/DevSkim-Action@v1

    - name: Upload DevSkim scan results to GitHub Security tab
      uses: github/codeql-action/upload-sarif@v2
      with:
        sarif_file: devskim-results.sarif
        
    - name: Analyze with SonarCloud         
      uses: SonarSource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GIT_ACCESS_TOKEN }}  # Needed to get PR information
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}   # Generate a token on Sonarcloud.io, add it to the secrets of this repo with the name SONAR_TOKEN (Settings > Secrets > Actions > add new repository secret)
      with:
        # Additional arguments for the sonarcloud scanner
        args:        
          -Dsonar.projectKey=avadevopspractice_SampleDemoApp
          -Dsonar.organization=avadevopspractice    
     
    # Connect to Azure Container Registry (ACR)
    - uses: azure/docker-login@v1
      with:
        login-server: ${{ env.REGISTRY_NAME }}.azurecr.io
        username: ${{ secrets.service_principal }} 
        password: ${{ secrets.service_principal_password }}
    
    # Container build and push to a Azure Container Registry (ACR)
    - name: ACR Push
      id: acr
      uses: azure/acr-build@v1
      with:
        service_principal: ${{ secrets.service_principal }}
        service_principal_password: ${{ secrets.service_principal_password }}
        tenant: ${{ secrets.tenant }}
        registry: ${{ secrets.registry }}
        repository: ${{ secrets.repository }}
        image: ${{ env.APP_NAME }}
        tag: ${{github.run_number}}
        git_access_token: ${{ secrets.git_access_token }}
        dockerfile: azure-vote/Dockerfile
        branch: master
    
  createSecret:
    permissions:
      contents: read
      id-token: write
    runs-on: ubuntu-latest
    needs: [build]
    steps:
    # Logs in with your Azure credentials
    - name: Azure login
      uses: Azure/login@v1
      with:
        creds: '{"clientId":"${{ secrets.service_principal }}","clientSecret":"${{ secrets.service_principal_password }}","subscriptionId":"${{ secrets.subscription_id }}","tenantId":"${{ secrets.tenant }}"}'

    # Retrieves your Azure Kubernetes Service cluster's kubeconfig file
    - name: Get K8s context
      uses: azure/aks-set-context@v2.0
      with:
        resource-group: ${{ env.CLUSTER_RESOURCE_GROUP }}
        cluster-name: ${{ env.CLUSTER_NAME }}

    # Retrieves the credentials for pulling images from your Azure Container Registry
    - name: Get ACR credentials
      run: |
        az acr update -n ${{ env.REGISTRY_NAME }} -g ${{ env.CLUSTER_RESOURCE_GROUP }} --admin-enabled true
        ACR_USERNAME=$(az acr credential show -g ${{ env.CLUSTER_RESOURCE_GROUP }} -n ${{ env.REGISTRY_NAME }} --query username -o tsv)
        ACR_PASSWORD=$(az acr credential show -g ${{ env.CLUSTER_RESOURCE_GROUP }} -n ${{ env.REGISTRY_NAME }} --query passwords[0].value -o tsv)
        echo "::add-mask::${ACR_USERNAME}"
        echo "::set-output name=username::${ACR_USERNAME}"
        echo "::add-mask::${ACR_PASSWORD}"
        echo "::set-output name=password::${ACR_PASSWORD}"
      id: get-acr-creds

    # Creates a kubernetes secret on your Azure Kubernetes Service cluster that matches up to the credentials from the last step
    - name: Create K8s secret for pulling image from ACR
      uses: Azure/k8s-create-secret@v1.1
      with:
        container-registry-url: ${{ env.REGISTRY_NAME }}.azurecr.io
        container-registry-username: ${{ steps.get-acr-creds.outputs.username }}
        container-registry-password: ${{ steps.get-acr-creds.outputs.password }}
        secret-name: ${{ env.SECRET }}  

  deploy:
    permissions:
      actions: read
      contents: read
      id-token: write
    runs-on: ubuntu-latest
    needs: [createSecret]
    steps:  
    # Checks out the repository this file is in
    - uses: actions/checkout@v3
    
    # Logs in with your Azure credentials
    - name: Azure login
      uses: Azure/login@v1
      with:
        creds: '{"clientId":"${{ secrets.service_principal }}","clientSecret":"${{ secrets.service_principal_password }}","subscriptionId":"${{ secrets.subscription_id }}","tenantId":"${{ secrets.tenant }}"}'
      
    # Retrieves your Azure Kubernetes Service cluster's kubeconfig file
    - name: Get K8s context
      uses: azure/aks-set-context@v2.0
      with:
        resource-group: ${{ env.CLUSTER_RESOURCE_GROUP }}
        cluster-name: ${{ env.CLUSTER_NAME }}        
        
    - name: Replace tokens
      # You may pin to the exact commit or the version.
      # uses: cschleiden/replace-tokens@4f7e3d67f3ff2317ae650842145cdbaefba65189
      uses: cschleiden/replace-tokens@v1.1
      env: 
        run_number: ${{ github.run_number }}
      with:
        tokenPrefix: '#{'
        tokenSuffix: '}#'
        files: azure-vote-all-in-one-redis.yaml
        
    # Deploy app to AKS
    - uses: azure/k8s-deploy@v1
      with:
        manifests: azure-vote-all-in-one-redis.yaml
        images: |
          ${{ env.REGISTRY_NAME }}.azurecr.io/${{ env.APP_NAME }}:${{github.run_number}}
        imagepullsecrets: |
          ${{ env.SECRET }}
        namespace: ${{ env.NAMESPACE }}
